### ISSUE TITLE
Allow IterableBatchTransactionExecutor to handle ResourceIterator<Node>

### ISSUE THREAD

**Issue by ikwattro** [graphaware/neo4j-framework#18]
Currently, we have to use `GlobalGraphOperations` in order to use the `IterableBatchTransactionExecutor` from the framework.

The GGO is deprecated and thus I think it would be nice to support the new database methods that returns `ResourceIterator<Node>` or `ResourceIterator<Relationship>`

**Comment by bachmanm** [comment]
In latest version, you'll be able to pass in an Iterator as well. Just be careful, the arguments come in a different order (quickfix because of java type erasure). So you now have:

`public IterableInputBatchTransactionExecutor(GraphDatabaseService database, int batchSize, final TransactionCallback<Iterable<T>> callback, UnitOfWork<T> unitOfWork)`

and 

`public IterableInputBatchTransactionExecutor(GraphDatabaseService database, int batchSize, UnitOfWork<T> unitOfWork, final TransactionCallback<Iterator<T>> callback)`
