### ISSUE TITLE
Support for Neo4J 3.3

### ISSUE THREAD

**Issue by TNAJanssen** [graphaware/neo4j-framework#79]
When are you going to support this version?

**Comment by jasperblues** [comment]
Out of curiosity, I had a go a look building against 3.3.0. Just to share what I found: 

- There are some changes to `org.neo4j.kernel.configuration.Config` and `Settings`
- Shutdown of a database obtained from `TestGraphDatabaseFacadeFactory` does not release the file lock. Didn't see the root cause - perhaps something moved off the main thread. Should be possible to fix, but failing that can instantiate the database with a specific storage path, and clean up manually.

**Comment by bachmanm** [comment]
Released for 3.3.0
